const genreData = {
  "Literature & Fiction": {
    "Literary Fiction": [
      "Action and Adventure",
      "Anthologies and Literature Collections",
      "African American",
      "British",
      "Classics",
    ],
    " Contemporary Fiction": [
      "Humor& Satire",
      "Women Fiction",
      "Drama and Play",
      "Mythology & Folk Tales",
    ],
  },

  "Children Books": [
    "Action and Adventure",
    "Animals",
    "Biographical Stories",
    "Comics",
    "Graphic Novels",
  ],
  "Comics, Manga and Graphic Novels": [
    "Comic Strips and Cartoons",
    "Fantasy",
    "Science Fiction",
    "Superhero",
  ],

  "Religious Fiction": {
    Christian: [
      "Apocalypse",
      "Contemporary",
      "Fantasy",
      "Historical",
      "Horror",
      "Inspirational",
      "Romance",
      "Supernatural",
    ],
    others: [
      "Apocalypse",
      "Fantasy",
      "Historical Fiction",
      "Horror",
      "Medical",
      "Metaphysical",
      "Romance",
      "Sagas",
      "Short Stories",
      "Teen and Young Adult",
    ],
    Islamic: [
      "Apocalypse",
      "Contemporary",
      "Fantasy",
      "Historical",
      "Horror",
      "Romance",
      "Supernatural",
    ],
  },
  "Mystery, Thriller and Suspense": {
    "Crime Fiction": [
      "General",
      "Heist",
      "Kidnapping",
      "Murder",
      "Police Procedurals",
      "Private Investigators",
    ],
    Suspense: [
      "Occult", 
      "Ghosts", 
      "Political"],
    Thriller: [
      "Assasination",
      "Conspiracies",
      "Espionage",
      "Financial",
      "Legal",
      "Medical",
      "Political",
      "Terrorism",
    ],
    Mystery: [
      "Detectives",
      "Hard boiled",
      "Historical",
      "International",
      "Paranormal",
      "Private Inv",
      "women sleuth",
    ],
    "Science Fiction": [
      "Futuristic", 
      "Space/Time travel",
      "Speculative", 
    ],
  },
  Romance: {
    others: [
      "Action & Adventure",
      "Adaptations",
      "Alpha Male",
      "Black American",
      "Clean & Wholesome",
      "Comedy",
      "Erotic",
      "Fantasy",
      "Historical",
      "Love Triangle",
      "Mafia Romance",
      "Medical",
      "Military",
      "Millionaires & Billionaires",
      "Multicultural & Interracial",
      "Workplace",
    ],
    "Young Adult": ["Coming of Age", "Teen"],
  },
  "Science Fiction & Fantasy": {
    Fantasy: [
      "Afrofuturism",
      "Apocalyptic",
      "Coming of Age",
      "Dark Fantasy",
      "Fairy Tales",
      "Folklore",
      "Metaphysical & Visionary",
      "Mythology",
      "Post-Apocalyptic",
      "Romance",
      "Superhero",
      "Sword & Sorcery",
      "Utopian and Dystopian",
    ],
    "Science Friction": [
      "Adventure",
      "Afrofuturism",
      "Alien Invasion",
      "Colonization",
      "Cyberpunk",
      "Dystopian",
      "Galactic Empire",
      "Genetic Engineering",
      "Post-Apocalyptic",
      "Space Exploration",
      "Space Opera",
      "speculative",
      "Time Travel",
    ],
  },
};

export default genreData;