const genreData = {
  "Literature & Fiction": {
    "Literary Fiction": [
      "Action and Adventure",
      "Anthologies and Literature Collections",
      "African American",
      "British",
      "Classics",
    ],
    " Contemporary Fiction": [
      "Humor& Satire",
      "Women Fiction",
      "Drama and Play",
      "Mythology & Folk Tales",
    ],
  },

  "Children Books": [
    "Action and Adventure",
    "Animals",
    "Biographical Stories",
    "Comics",
    "Graphic Novels",
  ],
  "Comics, Manga and Graphic Novels": [
    "Comic Strips and Cartoons",
    "Fantasy",
    "Science Fiction",
    "Superhero",
  ],

  "Religious Fiction": {
    Christian: [
      "Apocalypse",
      "Inspirational",
      "Fantasy",
      "Historical",
      "Contemporary",
      "Horror",
      "Supernatural",
      "Romance",
    ],
    all: [
      "Apocalypse",
      "Teen and Young Adult",
      "Historical Fiction",
      "Horror",
      "Short Stories",
      "Sagas",
      "Medical",
      "Fantasy",
      "Metaphysical",
      "Romance",
    ],
    Islamic: [
      "Apocalypse",
      "Fantasy",
      "Historical",
      "Contemporary",
      "Horror",
      "Supernatural",
      "Romance",
    ],
  },
  "Mystery, Thriller and Suspense": {
    "Crime Fiction": [
      "Heist",
      "Kidnapping",
      "Murder",
      "General",
      "Police procedurals",
      "Private Inv",
    ],
    Suspense: ["Ghosts", "Occult", "Political"],
    Thriller: [
      "Assasination",
      "Espionage",
      "Conspiracies",
      "Terrorism",
      "Medical",
      "Political",
      "Legal",
      "Financial",
    ],
    Mystery: [
      "Hard boiled",
      "International",
      "Detectives",
      "Historical",
      "women sleuth",
      "Private Inv",
      "Paranormal",
    ],
    "Science Fiction": ["Speculative", "Futuristic", "Space/Time travel"],
  },
  "Religion and Spirituality": [
    "Christian Fiction",
    "Islamic Fiction",
    "Inspirational Fiction",
    "Spirituality",
  ],
  Romance: [
    "Action & Adventure",
    "Love Triangle",
    "Adaptations",
    "Alpha Male",
    "Mafia Romance",
    "Medical",
    "Military",
    "Millionaires & Billionaires",
    "Multicultural & Interracial",
    "Black American",
    "Young Adult",
    "Coming of Age",
    "Erotic",
    "Clean & Wholesome",
    "Comedy",
    "Workplace",
    "Historical",
  ],
  "Science Fiction & Fantasy": [
    "Fantasy",
    "Superhero",
    "Fairy Tales",
    "Dark Fantasy",
    "Mythology",
    "Folklore",
    "Utopian and Dystopian",
    "Metaphysical & Visionary",
    "Coming of Age",
    "Sword & Sorcery",
    "Apocalyptic",
    "Post-Apocalyptic",
    "Adventure",
    "Genetic Engineering",
    "Alien Invasion",
    "Cyberpunk",
    "Space Exploration",
    "Galactic Empire",
    "Space Opera",
    "Time Travel",
    "Dystopian",
    "Colonization",
  ],
};

export default genreData;