const genreData = {
  "Literature & Fiction": [
    "Children Books",
    "Action and Adventure",
    "Comics, Manga and Graphic Novels",
    "Ages 9-12",
    "Animals",
    "Biographical Stories",
    "Comics",
    "Graphic Novels",
  ],
  "Comics, Manga and Graphic Novels": [
    "Artbooks",
    "Comic Strips and Cartoons",
    "Fantasy Graphic Novels",
    "Science Fiction Graphic Novels",
    "Superhero Graphic Novels",
  ],
  "Mystery, Thriller and Suspense": [
    "Crime Fiction",
    "Heist",
    "Kidnapping",
    "Murder",
    "General",
    "Police Procedurals",
    "Private Investigations",
    "Suspense",
    "Ghosts",
    "Occult",
    "Psychological",
    "Political",
  ],
  "Religion and Spirituality": [
    "Christian Fiction",
    "Islamic Fiction",
    "Inspirational Fiction",
    "Spirituality",
  ],
  Romance: [
    "Action & Adventure",
    "Love Triangle",
    "Adaptations",
    "Alpha Male",
    "Mafia Romance",
    "Medical",
    "Military",
    "Millionaires & Billionaires",
    "Multicultural & Interracial",
    "Black American",
    "Young Adult",
    "Coming of Age",
    "Erotic",
    "Clean & Wholesome",
    "Comedy",
    "Workplace",
    "Historical",
  ],
  "Science Fiction & Fantasy": [
    "Fantasy",
    "Superhero",
    "Fairy Tales",
    "Dark Fantasy",
    "Mythology",
    "Folklore",
    "Utopian and Dystopian",
    "Metaphysical & Visionary",
    "Coming of Age",
    "Sword & Sorcery",
    "Apocalyptic",
    "Post-Apocalyptic",
    "Adventure",
    "Genetic Engineering",
    "Alien Invasion",
    "Cyberpunk",
    "Space Exploration",
    "Galactic Empire",
    "Space Opera",
    "Time Travel",
    "Dystopian",
    "Colonization",
  ],
};

export default genreData;