"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faXTwitter,
  faFacebookF,
  faLinkedinIn,
  faInstagram,
} from "@fortawesome/free-brands-svg-icons";

import { usePathname } from "next/navigation";
import Link from "next/link";

import { FormProvider } from "../context/FormContext";

config.autoAddCss = false;

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  const isSignIn = pathname.endsWith("/author/sign_in");
  const isSignUp = pathname.endsWith("/author/sign_up");
  const isRegPage = isSignIn || isSignUp;

  const authorPages =
    pathname.startsWith("/author") || pathname.startsWith("/dashboard");

  return (
    <html lang="en">
      <body className={`z-10 ${isRegPage ? "bg-slate-800" : ""}`}>
        <nav className={`${authorPages ? "hidden" : ""}`}>
          <div>
            <Link href="/">
              <img src="/images/logo.png" alt="logo" />
              <p className="text-red-700">Global Publishing</p>
            </Link>
            <div>
              <Link
                href="/author/sign_in"
                className="bg-slate-700 text-white cursor-pointer"
              >
                Sign in
              </Link>
              <Link
                href="/author/sign_up"
                className="bg-[#EF5353] text-white cursor-pointer"
              >
                Join Itan
              </Link>
            </div>
          </div>

          <ul>
            <Link href="/" className="hover:text-[#EF5353] cursor-pointer">
              <li>About Itan</li>
            </Link>
            <Link
              href="/publish"
              className="hover:text-[#EF5353] cursor-pointer"
            >
              <li>Publish</li>
            </Link>
            <Link
              href="/monetize"
              className="hover:text-[#EF5353] cursor-pointer"
            >
              <li className="hover:text-[#EF5353] cursor-pointer">Monetize</li>
            </Link>
            <Link href="#" className="hover:text-[#EF5353] cursor-pointer">
              <li>Help</li>
            </Link>
          </ul>
        </nav>
        <FormProvider>{children}</FormProvider>

        <footer className={`${authorPages ? "hidden" : ""} mt-10`}>
          <section className="relative z-30 h-[170px] flex flex-col items-center justify-center text-center">
            {/* Background image */}
            <div
              className="absolute inset-0 bg-cover bg-center bg-no-repeat"
              style={{ backgroundImage: "url('/images/footer-bg-img.jpeg')" }}
            ></div>

            {/* Full-screen backdrop to reduce image sharpness */}
            <div className="absolute inset-0 bg-black/70 "></div>

            <div className="relative z-10 w-full text-white mb-3 ">
              <h2 className="mx-auto text-center text-lg font-semibold">
                Get in touch with us
              </h2>
              <p className="mx-auto text-center mt-1 text-xs">
                You can subscribe to our daily newsletter and be updated with
                itan
              </p>
            </div>

            <div className="relative z-10 flex justify-center p-1 bg-white backdrop-blur-md rounded-md">
              <input
                type="email"
                placeholder="Enter email address"
                className="flex-1 border-0 outline-none ring-0 focus:ring-0"
              />
              <button className="text-white bg-[#EF5353] px-6 py-2 rounded-md cursor-pointer">
                Subscribe
              </button>
            </div>
          </section>

          <section className="bg-[#111928]">
            <div className="mx-3 pt-8">
              <Link href="/">
                <img src="/images/logo.png" alt="logo" className="h-8 w-12" />
              </Link>
            </div>

            <div className="text-white flex flex-col-reverse">
              <div className="flex mx-3 mt-3">
                <p className="hidden sm:block">
                  Itan is a revolutionary publishing platform designed
                  specifically for writers like you. Seamlessly publish your
                  work to a global audience, retaining creative control and
                  ownership every step of the way.
                </p>
                <div className="hidden sm:block">
                  <h3>Menu</h3>
                  <p>Sign In</p>
                  <p>Sign Up</p>
                  <p>Services</p>
                  <p>How it works</p>
                  <p>Testimonial</p>
                </div>

                <div className="mr-10 ">
                  <h3 className="text-lg font-semibold">Resources</h3>
                  <p>New update</p>
                  <p>Documentation</p>
                  <p>Blog</p>
                </div>

                <div>
                  <h3 className="text-lg font-semibold">About</h3>
                  <p>Contact</p>
                  <p>About</p>
                </div>

                <div className="hidden sm:block">
                  <h3>Contact</h3>
                  <p>Contact</p>
                  <p>234-8161-7963-71</p>
                </div>
              </div>

              <div className="mx-3 mt-6 flex justify-between w-48">
                <Link href="#">
                  <FontAwesomeIcon
                    icon={faLinkedinIn}
                    className="w-4 h-6 p-2 rounded-full border-2 border-[#EF5353] hover:bg-[#EF5353]"
                  />
                </Link>
                <Link href="https://x.com/ItanGlobal">
                  <FontAwesomeIcon
                    icon={faXTwitter}
                    className="w-4 h-6 p-2 rounded-full border-2 border-[#EF5353] hover:bg-[#EF5353]"
                  />
                </Link>

                {/* <Link></Link> */}
                <Link href="https://web.facebook.com/itanglobalpublishing/">
                  <FontAwesomeIcon
                    icon={faFacebookF}
                    className="w-4 h-6 p-2 rounded-full border-2 border-[#EF5353] hover:bg-[#EF5353]"
                  />
                </Link>

                <Link href="https://www.instagram.com/itanglobalpublishing">
                  <FontAwesomeIcon
                    icon={faInstagram}
                    className="w-4 h-6 p-2 rounded-full border-2 border-[#EF5353] hover:bg-[#EF5353]"
                  />
                </Link>
              </div>
            </div>
            <div className="text-white flex items-center ml-3 mt-4">
              <p className="mr-4">Terms & Conditions</p>
              <p>Privacy Policy</p>
            </div>
            <div className="text-white flex items-center ml-3 pb-10">
              <img
                src="/images/copy-right.png"
                alt="copy right"
                className="h-4 w-4 mr-1"
              />
              <p>Copyright 2025 itan. All Rights Reserved.</p>
            </div>
          </section>
        </footer>
      </body>
    </html>
  );
}
