"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "flowbite";
import "./globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";

import { usePathname } from "next/navigation";
import TopNav from "../components/TopNav";
import SubMenuNav from "../components/SubMenuNav";
import Footer from "../components/Footer";
// import { FormProvider } from "../context/FormContext";

config.autoAddCss = false;

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  const isSignIn = pathname.endsWith("/author/sign_in");
  const isSignUp = pathname.endsWith("/author/sign_up");
  const isRegPage = isSignIn || isSignUp;

  const authorPages =
    pathname.startsWith("/author") || pathname.startsWith("/dashboard");

  return (
    <html lang="en">
      <body className={`z-10 ${isRegPage ? "bg-slate-800" : ""}`}>
        <main className="w-full min-h-screen">
          <div className={`${authorPages ? "hidden" : ""}`}>
            <div className="">
              <TopNav />
              <SubMenuNav />
              <div className="px-4 py-10 large:py-4 xl:py-0 xl:px-8">
                {children}
              </div>
              <Footer />
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}

