"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css"; // Prevent fontawesome from adding styles automatically
import { usePathname } from "next/navigation";

import { FormProvider } from "../context/FormContext";

config.autoAddCss = false;

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  const isSignIn = pathname.endsWith("/author/sign_in");
  const isSignUp = pathname.endsWith("/author/sign_up");
  const isRegPage = isSignIn || isSignUp;

  const authorPages =
    pathname.startsWith("/author") || pathname.startsWith("/dashboard");

  return (
    <html lang="en">
      <body className={`z-10 ${isRegPage ? "bg-slate-800" : ""}`}>
        <nav className={`${authorPages ? "hidden" : ""}`}>
          <div>
            <div>
              <img src="/images/logo.png" alt="logo" />
              <p className="text-red-700">Global Publishing</p>
            </div>
            <div>
              <button>Sign</button>
              <button>Join Itan</button>
            </div>
          </div>

          <ul>
            <li>About Itan</li>
            <li>liublish</li>
            <li>Monetize</li>
            <li>Helli</li>
          </ul>
        </nav>
        <FormProvider>{children}</FormProvider>

        <footer className={`${authorPages ? "hidden" : ""}`}>
          <h2>Get in touch with us</h2>
          <p>
            You can subscribe to our daily newsletter and be updated with itan
          </p>

          <div>
            <input type="email" placeholder="Enter email address" />
            <button>Subscribe</button>
          </div>

          <section>
            <div>
              <img src="/images/logo.png" alt="logo" />
              <p>
                Itan is a revolutionary publishing platform designed
                specifically for writers like you. Seamlessly publish your work
                to a global audience, retaining creative control and ownership
                every step of the way.
              </p>
            </div>

            <div>
              <h3>Menu</h3>
              <p>Sign In</p>
              <p>Sign Up</p>
              <p>Services</p>
              <p>How it works</p>
              <p>Testimonial</p>
            </div>

            <div>
              <h3>Resources</h3>
              <p>New update</p>
              <p>Documentation</p>
              <p>Blog</p>
            </div>

            <div>
              <h3>About</h3>
              <p>Contact</p>
              <p>About</p>
            </div>

            <div>
              <h3>Contact</h3>
              <p>Contact</p>
              <p>234-8161-7963-71</p>
              <img
                src="/images/twitter-logo.png"
                alt="twitter"
                className="bg-slate-800"
              />
              <img
                src="/images/facebook-logo.png"
                alt="facebook"
                className="bg-slate-800"
              />
              <img
                src="images/linkedin-logo.png"
                alt="linkedin"
                className="bg-slate-800"
              />
              <img
                src="/images/whatsapp-logo.png"
                alt="whatsapp"
                className="bg-slate-800"
              />
            </div>
          </section>
        </footer>
      </body>
    </html>
  );
}
